/*
 * File: app/model/libro.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.libro', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'libro_id'
        },
        {
            name: 'libro_nombre'
        },
        {
            name: 'libro_autor'
        },
        {
            name: 'libro_editorial'
        },
        {
            name: 'libro_fecha'
        },
        {
            name: 'carrera_nombre'
        },
        {
            name: 'semestre_periodo'
        },
        {
            name: 'curso_nombre'
        },
        {
            name: 'archivospdf'
        }
    ]
});