/*
 * File: app/view/ingresolibro.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ingresolibro', {
    extend: 'Ext.window.Window',
    alias: 'widget.ingresolibro',

    requires: [
        'MyApp.view.ingresolibroViewModel',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.File',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'ingresolibro'
    },
    modal: true,
    autoShow: true,
    height: 365,
    width: 611,
    title: 'INGRESO DE LIBROS',

    items: [
        {
            xtype: 'form',
            height: 324,
            layout: 'column',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    id: 'libro_nombre',
                    margin: '10 0 0 0',
                    width: 276,
                    fieldLabel: 'Titulo:',
                    name: 'libro_nombre',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    disabled: true,
                    id: 'libro_id',
                    margin: '10 0 0 5',
                    width: 168,
                    fieldLabel: 'ID',
                    name: 'libro_id',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    id: 'libro_editorial',
                    margin: '10 0 0 0',
                    width: 276,
                    fieldLabel: 'Editorial:',
                    name: 'libro_editorial',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    id: 'libro_autor',
                    margin: '15 0 0 5',
                    width: 273,
                    fieldLabel: 'Autor:',
                    name: 'libro_autor',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    id: 'libro_fecha',
                    margin: '15 0 0 0',
                    width: 276,
                    fieldLabel: 'Fecha:',
                    name: 'libro_fecha',
                    allowBlank: false
                },
                {
                    xtype: 'combobox',
                    id: 'carrera_id',
                    margin: '15 0 0 5',
                    width: 273,
                    fieldLabel: 'Carrera',
                    name: 'carrera_id',
                    allowBlank: false,
                    blankText: 'Escoge una carrera...',
                    enableKeyEvents: true,
                    selectOnFocus: true,
                    displayField: 'carrera_nombre',
                    store: 'storeCarrera',
                    typeAhead: true,
                    valueField: 'carrera_id'
                },
                {
                    xtype: 'combobox',
                    id: 'curso_id',
                    margin: '15 0 0 0',
                    fieldLabel: 'Curso',
                    name: 'curso_id',
                    allowBlank: false,
                    blankText: 'Escoge un curso...',
                    enableKeyEvents: true,
                    selectOnFocus: true,
                    displayField: 'curso_nombre',
                    store: 'storeCurso',
                    typeAhead: true,
                    valueField: 'curso_id'
                },
                {
                    xtype: 'combobox',
                    id: 'semestre_id',
                    margin: '15 0 0 5',
                    width: 272,
                    fieldLabel: 'Semestre:',
                    name: 'semestre_id',
                    allowBlank: false,
                    blankText: 'Escoge un periodo...',
                    enableKeyEvents: true,
                    selectOnFocus: true,
                    displayField: 'semestre_periodo',
                    store: 'storeSemestre',
                    typeAhead: true,
                    valueField: 'semestre_id'
                },
                {
                    xtype: 'filefield',
                    id: 'FileInput',
                    margin: '20 0 0 105',
                    width: 380,
                    fieldLabel: 'Subir PDF',
                    msgTarget: 'side',
                    name: 'FileInput',
                    allowBlank: false,
                    emptyText: 'Seleccione archivo...'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 67,
                    items: [
                        {
                            xtype: 'button',
                            action: 'grabarlibro',
                            margin: '0 0 0 220',
                            icon: 'img/filesave.png',
                            text: 'Grabar'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form = this.up('form').getForm();
                                var win2 = button.up('ingresolibro');

                                if(mode=='Agregar'){
                                    if(form.isValid()){
                                        form.submit({
                                            url:'GuardarPersonal.php',
                                            method: 'POST',
                                            params:{
                                                FileInput:FileInput,
                                                libro_nombre:libro_nombre,
                                                libro_autor:libro_autor,
                                                libro_editorial:libro_editorial,
                                                libro_fecha:libro_fecha,
                                                carrera_id:carrera_id,
                                                semestre_id:semestre_id,
                                                curso_id:curso_id
                                            },
                                            waitMsg:'Subiendo archivo...',
                                            success:function(response){
                                                alert('Registrado correctamente...');
                                                var store = Ext.getStore('storeLibro');
                                                Ext.getCpm('grid');
                                                store.load({
                                                    params:{
                                                        libro_nombre:libro_nombre
                                                    }
                                                });
                                                win2.close();
                                                return;
                                            },
                                            failure: function(response){
                                                Ext.Msg.alert('Mensaje','Error en el servidor');
                                            }

                                        });
                                    }
                                }
                            },
                            action: 'guardarPDF',
                            margin: '',
                            icon: 'img/exit.png',
                            text: 'Guardar PDF'
                        },
                        {
                            xtype: 'button',
                            action: 'salir2',
                            icon: 'img/salir.png',
                            text: 'Salir'
                        }
                    ]
                }
            ]
        }
    ]

});