/*
 * File: app/view/menu.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.menu', {
    extend: 'Ext.window.Window',
    alias: 'widget.menu',

    requires: [
        'MyApp.view.menuViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'menu'
    },
    autoShow: true,
    height: 133,
    width: 446,
    title: 'MENÚ',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'right',
            height: 135,
            width: 315,
            vertical: true,
            items: [
                {
                    xtype: 'button',
                    action: 'openAdmin',
                    icon: 'img/add_user.png',
                    text: 'MODULO ADMINISTRADOR'
                },
                {
                    xtype: 'button',
                    action: 'openUser',
                    icon: 'img/rh.png',
                    text: 'MODULO USUARIO'
                }
            ]
        }
    ]

});