/*
 * File: app/view/MyGridPanel.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mygridpanel',

    requires: [
        'MyApp.view.MyGridPanelViewModel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'mygridpanel'
    },
    modal: true,
    autoShow: true,
    height: 548,
    width: 1016,
    title: '',
    store: 'storeLibro',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 39,
            dataIndex: 'libro_id',
            text: 'N°'
        },
        {
            xtype: 'gridcolumn',
            width: 177,
            dataIndex: 'libro_nombre',
            text: 'TITULO'
        },
        {
            xtype: 'gridcolumn',
            width: 149,
            dataIndex: 'libro_autor',
            text: 'AUTOR'
        },
        {
            xtype: 'gridcolumn',
            width: 111,
            dataIndex: 'libro_editorial',
            text: 'EDITORIAL'
        },
        {
            xtype: 'gridcolumn',
            width: 92,
            dataIndex: 'libro_fecha',
            text: 'FECHA'
        },
        {
            xtype: 'gridcolumn',
            width: 124,
            dataIndex: 'carrera_nombre',
            text: 'CARRERA'
        },
        {
            xtype: 'gridcolumn',
            width: 92,
            dataIndex: 'semestre_periodo',
            text: 'SEMESTRE'
        },
        {
            xtype: 'gridcolumn',
            width: 106,
            dataIndex: 'curso_nombre',
            text: 'CURSO'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    action: 'addLibro',
                    icon: 'img/add.png',
                    text: 'Agregar'
                },
                {
                    xtype: 'button',
                    action: 'editLibro',
                    icon: 'img/bogus.png',
                    text: 'Editar'
                },
                {
                    xtype: 'button',
                    action: 'eliminarLibro',
                    icon: 'img/delete_row.gif',
                    text: 'Eliminar'
                },
                {
                    xtype: 'button',
                    action: 'salir1',
                    icon: 'img/exit.png',
                    text: 'Salir'
                }
            ]
        }
    ]

});