/*
 * File: app/view/windowusuario.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.windowusuario', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowusuario',

    requires: [
        'MyApp.view.windowusuarioViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'windowusuario'
    },
    autoShow: true,
    height: 460,
    width: 711,
    title: 'MÓDULO USUARIO',

    items: [
        {
            xtype: 'gridpanel',
            height: 396,
            title: '',
            store: 'storeUsuario',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 63,
                    dataIndex: 'libro_id',
                    text: 'N°'
                },
                {
                    xtype: 'gridcolumn',
                    width: 166,
                    dataIndex: 'libro_nombre',
                    text: 'NOMBRE DEL LIBRO'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'libro_autor',
                    text: 'AUTOR'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value) {
                            return '<a href="' + value + '" target="_blank">Abrir PDF</a>';
                        }
                        return 'No disponible';
                    },
                    width: 148,
                    dataIndex: 'archivospdf',
                    text: 'ARCHIVOS PDF'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler1: function(button) {
                                var grid = button.up('gridpanel');
                                var libroNombre = grid.down('libro_buscado').getValue();
                                var store = grid.getStore();

                                store.load({
                                    params: {
                                        libro_nombre: libroNombre
                                    },
                                    callback: function(records, operation, success) {
                                        if (success) {
                                            if (records.length === 0) {
                                                Ext.Msg.alert('Mensaje', 'No se encontraron resultados.');
                                            }
                                        } else {
                                            Ext.Msg.alert('Mensaje', 'Error en el servidor al buscar.');
                                        }
                                    }
                                });
                            },
                            text: 'Buscar'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'libro_buscado',
                            fieldLabel: 'Ingrese Libro:',
                            name: 'libro_buscado'
                        }
                    ]
                }
            ]
        }
    ]

});