/*
 * File: app/view/windowadmin.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.windowadmin', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowadmin',

    requires: [
        'MyApp.view.windowadminViewModel',
        'MyApp.view.MyGridPanel',
        'Ext.grid.Panel'
    ],

    viewModel: {
        type: 'windowadmin'
    },
    autoShow: true,
    height: 521,
    width: 947,
    title: 'MÓDULO ADMINISTRADOR',

    items: [
        {
            xtype: 'mygridpanel',
            height: 416
        }
    ]

});